name: Update GitHub package versions

on:
  push:
  schedule:
    - cron: 0 */3 * * *

jobs:
  update_github_releases:
    name: Update github package versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ["gilbertchen/duplicacy", "just-containers/s6-overlay"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Read repository version
        id: repository_version
        shell: bash
        run: |
          TAG=$(curl -Ls https://api.github.com/repos/${{ matrix.repository }}/tags | jq -r "first.name")
          VERSION=${TAG:1}
          BRANCH="packageupdaterbot/${{ matrix.repository }}-${VERSION}"
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=branch::${BRANCH}"
          echo "Repository version=${VERSION}, branch=${BRANCH}"

      - name: Update Dockerfile
        shell: bash
        run: |
          TEMPFILENAME=$(tempfile -d .)
          ESCAPED_SEARCH=$(printf '%s\n' "${{ matrix.repository }}" | sed -e 's/[\/&]/\\&/g')
          sed '/.*${ESCAPED_SEARCH}.*/{n;s/.*/ENV PACKAGEVERSION=\"${{ steps.repository_version.outputs.version }}\"/}' < Dockerfile > ${TEMPFILENAME}
          mv ${TEMPFILENAME} Dockerfile

      - name: Create Pull Request, Bump ${{ matrix.repository }} to ${{ steps.repository_version.outputs.version }}
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          branch: ${{ steps.repository_version.outputs.branch }}
          commit-message: Bump ${{ matrix.repository }} to ${{ steps.repository_version.outputs.version }}
          delete-branch: true
          title: Bump ${{ matrix.repository }} to ${{ steps.repository_version.outputs.version }}
          body: |
            Bump [${{ matrix.repository }}](https://github.com/${{ matrix.repository }}) to ${{ steps.repository_version.outputs.version }}.

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
